package org.ftc8702.opmodes.production;

public enum SkystoneAutoModeState {
    INIT,
    MOVE_TO_FIRST_ZONE,
    MOVE_FOR_TEST,
    MOVE_TO_FOUNDATION,
    MOVE_FROM_FOUNDATION,
    MOVE_TO_SECOND_ZONE,
    DETECT_SKYSTONE,
    HUG_STONE,
    MOVE_STONE_TO_BUIDER_ZONE,
    POSITION_TO_FOUNDATION,
    MOVE_FOUNDATION,
    LOWER_FOUNDATION_GRABBER,
    RAISE_FOUNDATION_GRABBER,
    PARK,
    DONE
}
