package org.ftc8702.opmodes.production;

public enum SkystoneAutoModeState {
    INIT,
    MOVE_TO_FIRST_ZONE,
    MOVE_FOR_TEST,
    SPIN_TO_WIN,
    MOVE_TO_SECOND_SKYSTONE,
    HUG_STONE2,
    MOVE_STONE_TO_BUILDER_ZONE2,
    MOVE_TO_FOUNDATION,
    MOVE_FROM_FOUNDATION,
    MOVE_TO_SECOND_ZONE,
    DETECT_SKYSTONE,
    GRAB_SKY_STONE,
    HUG_STONE,
    MOVE_STONE_TO_BUILDER_ZONE,
    POSITION_TO_FOUNDATION,
    MOVE_FOUNDATION,
    LOWER_FOUNDATION_GRABBER,
    RAISE_FOUNDATION_GRABBER,
    PARK,
    DONE
}
